### ISSUE TITLE
Fedora REST endpoint webpage only shows one `pcdm:hasMember` triple for `ldp:DirectContainer`s that have more than one such triple

### ISSUE THREAD

**Issue by markmatney** [fcrepo4-exts/fcrepo4-vagrant#48]
Following [this](https://wiki.duraspace.org/display/FEDORA4x/LDP-PCDM-F4+In+Action) guide, I encountered an error with the web UI when adding resources to `ldp:DirectContainer`s ([this](https://wiki.duraspace.org/display/FEDORA4x/LDP-PCDM-F4+In+Action#LDP-PCDM-F4InAction-Book-CreatePage0) step in particular). After `POST`ing `page0` to `/objects/raven/pages/`, a `GET` request to `/objects/raven/` lists two `pcdm:hasMember` triples, but the webpage at `localhost:8080/fcrepo/rest/objects/raven/` only lists one.

**Comment by acoburn** [comment]
This is an issue that has been fixed in master and will be part of the 4.6.0 release. See the following related tickets for more information: https://jira.duraspace.org/browse/FCREPO-1498 and https://jira.duraspace.org/browse/FCREPO-1742

The core of the issue related to ETags not being changed when LDP membership triples changed, so the HTML UI would present a stale view of the resource.

**Comment by markmatney** [comment]
Thanks for the info!

**Comment by emcaulay** [comment]
Wow, pretty interesting! Thank you both for this information.
